-- Mintapp — project_inquiries
--
-- Reproduces the live Supabase configuration for the Start a Project form's
-- storage table, as verified against the live project's Data API schema and
-- grant behavior on 2026-08-15 (see docs/supabase-database-permissions.md).
--
-- IMPORTANT — read before assuming this is byte-for-byte identical to production:
-- The application only ever talks to this project through the Data API
-- (PostgREST), by architecture decision — there is no direct Postgres
-- connection string available to introspect information_schema/pg_catalog.
-- Everything below marked "verified" was confirmed via the Data API's
-- OpenAPI schema output and/or a live behavioral test (see the doc above).
-- Everything marked "reconstructed" is a best-effort, standard-practice
-- implementation of something the live schema clearly implies (via a column
-- comment, a NOT NULL constraint, or a default value) but whose exact
-- original DDL text could not be independently confirmed through the Data
-- API alone. Before treating this migration as fully authoritative, diff it
-- against the live database via the Supabase SQL editor.
--
-- This migration was written directly against the live project's observed
-- state; it was not generated by (and does not require) the Supabase CLI.

-- Verified: gen_random_uuid() is used as the id default. Guarded here for
-- portability to Postgres versions where it isn't a core builtin yet.
create extension if not exists pgcrypto;

create table if not exists public.project_inquiries (
  id                     uuid primary key default gen_random_uuid(),
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  deleted_at             timestamptz,

  full_name              text not null,
  email                  text not null,
  phone                  text,
  company_name           text,
  company_url            text,
  country                text,

  preferred_language     text not null,
  project_type           text,
  project_description    text not null,
  budget_range           text,
  timeline               text,
  referral_source        text,

  consent_given          boolean not null default false,
  consent_at             timestamptz,

  lead_status            text not null default 'new',
  booking_status         text not null default 'not_booked',
  cal_booking_id         text,
  cal_booking_url        text,
  meeting_start_at       timestamptz,
  meeting_timezone       text,

  notification_status    text not null default 'pending',
  notification_sent_at   timestamptz,

  concept_pack_status    text not null default 'not_started',
  internal_notes         text,

  source_page            text,
  utm_source             text,
  utm_medium             text,
  utm_campaign           text,
  submission_error       text,

  -- Reconstructed: the live "consent_given" column comment explicitly
  -- references a "consent_required constraint" by name, which is strong
  -- evidence a check constraint like this exists. Named to match.
  constraint consent_required check (consent_given = true)
);

-- Verified table/column comments below are reproduced from the live
-- project's actual COMMENT ON ... text, retrieved via the Data API's
-- OpenAPI schema output — these are not invented.

comment on table public.project_inquiries is
  'Leads submitted through the public Start a Project form. Written only by the server-side API route via the Supabase secret key (Data API), never directly by browser clients.';

comment on column public.project_inquiries.deleted_at is
  'Soft-delete marker for internal archival only. NOT sufficient on its own for a verified personal-data erasure request — see retention policy.';

comment on column public.project_inquiries.consent_given is
  'Always true for any stored row (see consent_required constraint) — kept as an explicit, self-documenting evidentiary field even though it cannot be false in practice.';

comment on column public.project_inquiries.lead_status is
  'Business/sales pipeline stage only. Does NOT track meeting-booking (see booking_status) or internal-prep progress (see concept_pack_status) — avoid re-adding those meanings here.';

-- Reconstructed: indexes were not independently visible through the Data
-- API. These are standard, low-risk additions for the access patterns this
-- table clearly has (lookup by pipeline stage, recency ordering, lookup by
-- applicant email for support/deletion requests). Confirm against the live
-- database's actual indexes before assuming this list is exhaustive.
create index if not exists project_inquiries_created_at_idx on public.project_inquiries (created_at desc);
create index if not exists project_inquiries_lead_status_idx on public.project_inquiries (lead_status);
create index if not exists project_inquiries_email_idx on public.project_inquiries (email);

-- Reconstructed: updated_at is default now() on insert only; without a
-- trigger it would never change on update. Standard idiomatic
-- implementation — the live trigger's exact function name could not be
-- confirmed through the Data API, but this produces equivalent behavior.
create or replace function public.set_project_inquiries_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists project_inquiries_set_updated_at on public.project_inquiries;
create trigger project_inquiries_set_updated_at
  before update on public.project_inquiries
  for each row
  execute function public.set_project_inquiries_updated_at();

-- Verified: RLS is enabled with zero policies. This alone denies all
-- access to `anon` and `authenticated` — see docs/supabase-database-permissions.md
-- for why this is a separate, independent layer from the grants below.
alter table public.project_inquiries enable row level security;

-- Verified live via a direct, non-destructive behavioral test on
-- 2026-08-15 (SELECT succeeded; DELETE against a nonexistent id returned
-- 42501). No policies are created here — RLS stays enabled with none,
-- matching the live project.

-- Verified: exact minimum grants in production. No DELETE — see the doc
-- for why that's deliberate. No grants at all to anon/authenticated.
grant select, insert, update on public.project_inquiries to service_role;
